# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170305_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissions',
            options={},
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='name',
        ),
        migrations.AlterField(
            model_name='submissions',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
