# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_submit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='date',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
