# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_submit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=250)),
                ('date', models.URLField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='submit',
            name='date',
            field=models.DateField(),
        ),
    ]
