# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170411_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fact',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='fact',
            old_name='date',
            new_name='url',
        ),
    ]
