# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170411_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500)),
                ('person_name', models.CharField(max_length=250)),
                ('email', models.URLField(default='', max_length=1000)),
            ],
        ),
    ]
