# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='aboutlist',
        ),
    ]
