# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170411_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aboutlist',
            new_name='aboutl',
        ),
    ]
