# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170411_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutl',
            name='phone',
            field=models.IntegerField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
