# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_countydat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countydat',
            name='AvgAgeOlder',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='countydat',
            name='AvgAgeYounger',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='countydat',
            name='AvgBRChange',
            field=models.FloatField(max_length=5),
        ),
    ]
