# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 22:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170502_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='countydat',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=0, srid=4326),
            preserve_default=False,
        ),
    ]
