# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-14 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_countydat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutl',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
